import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BottomNav } from "@/components/bottom-nav";
import { AppHeader } from "@/components/app-header";
import { mockCaregiver } from "@/lib/mock-data";
import { UserCircle2, Phone, Settings, UserPlus, ShieldCheck } from "lucide-react";
import Link from "next/link";

export default function FamilyPage() {
  return <div className="app-shell"><AppHeader title="가족 연동" showBack /><div className="app-container space-y-5"><Card><CardHeader><CardTitle>연결된 보호자</CardTitle></CardHeader><CardContent><div className="list-tile flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-cyan-100"><UserCircle2 className="h-10 w-10 text-cyan-700" /></div><div className="flex-1"><p className="text-2xl font-bold">{mockCaregiver.name}</p><p className="text-lg text-slate-600">{mockCaregiver.relation}</p><p className="text-base text-slate-500">{mockCaregiver.phone}</p></div><Link href={`tel:${mockCaregiver.phone}`}><button className="flex h-12 w-12 items-center justify-center rounded-full bg-cyan-600 text-white shadow-sm"><Phone className="h-6 w-6" /></button></Link></div></CardContent></Card><Card><CardHeader><CardTitle>공유 설정</CardTitle></CardHeader><CardContent className="space-y-3">{[["체크인 공유","매일 상태 공유",true],["복약 누락 알림","2시간 이상 미복용 시",true],["위험 상황만 공유","도움 요청 시에만",false]].map(([title, copy, on]) => <div key={String(title)} className="list-tile flex items-center justify-between"><div><p className="text-xl font-bold">{title}</p><p className="text-base text-slate-500">{copy}</p></div><div className={`flex h-8 w-14 items-center rounded-full px-1 ${on ? "justify-end bg-cyan-500" : "bg-slate-300"}`}><div className="h-6 w-6 rounded-full bg-white" /></div></div>)}</CardContent></Card><Card className="bg-[linear-gradient(135deg,#ecfeff_0%,#ffffff_100%)]"><CardContent className="flex items-start gap-4 p-6"><div className="feature-icon"><ShieldCheck className="h-6 w-6" /></div><p className="text-lg leading-8 text-slate-700">보호자는 설정하신 정보만 받을 수 있어요. 언제든 공유 범위를 바꿀 수 있어서 부담이 적습니다.</p></CardContent></Card><div className="space-y-3"><Button variant="outline" className="w-full"><UserPlus className="h-6 w-6" />다른 보호자 추가</Button><Button variant="outline" className="w-full"><Settings className="h-6 w-6" />공유 설정 변경</Button></div></div><BottomNav /></div>;
}
