import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BottomNav } from "@/components/bottom-nav";
import { AppHeader } from "@/components/app-header";
import { weeklyReport } from "@/lib/mock-data";
import { CheckCircle, TrendingUp } from "lucide-react";

export default function ReportPage() {
  return <div className="app-shell"><AppHeader title="내 기록" /><div className="app-container space-y-5"><Card className="hero-panel border-0"><CardContent className="relative z-10 p-7 text-white"><p className="text-lg opacity-80">이번 주 달성률</p><p className="mt-2 text-6xl font-bold">{weeklyReport.checkInRate}%</p><div className="mt-4 flex items-center gap-2 text-lg"><TrendingUp className="h-6 w-6" />지난주보다 15% 증가했어요</div></CardContent></Card><Card><CardHeader><CardTitle>주간 요약</CardTitle></CardHeader><CardContent className="space-y-3">{[["체크인", weeklyReport.checkInDays, weeklyReport.checkInRate, "teal"],["복약", weeklyReport.medicationDays, weeklyReport.medicationRate, "blue"],["운동", weeklyReport.exerciseDays, weeklyReport.exerciseRate, "green"]].map(([title, days, rate, tone]) => <div key={String(title)} className="list-tile flex items-center justify-between"><div className="flex items-center gap-4"><div className="feature-icon"><CheckCircle className={`h-6 w-6 ${tone === "blue" ? "text-blue-600" : tone === "green" ? "text-emerald-600" : "text-cyan-700"}`} /></div><div><p className="text-xl font-bold">{title}</p><p className="text-base text-slate-500">{days}/{weeklyReport.totalDays}일</p></div></div><div className="text-3xl font-bold text-slate-900">{rate}%</div></div>)}</CardContent></Card><Card className="bg-amber-50/80"><CardContent className="p-6"><h3 className="text-2xl font-bold text-amber-950">이번 주 칭찬</h3><p className="mt-3 text-lg leading-8 text-amber-900/90">이번 주 6일 연속 체크인을 완료하셨어요. 작은 습관이 꾸준히 이어지고 있어요. 정말 잘하고 계십니다.</p></CardContent></Card></div><BottomNav /></div>;
}
