import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { mockUser } from "@/lib/mock-data";
import { ArrowLeft, Bell, AlertCircle, Shield } from "lucide-react";
import Link from "next/link";

export default function CaregiverSettingsPage() {
  return <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(191,219,254,0.34),_transparent_30%),linear-gradient(180deg,_#f8fbff_0%,_#eef4fb_100%)]"><div className="page-container-narrow py-8 space-y-5"><div className="surface-card p-6"><div className="flex items-center gap-4"><Link href="/caregiver"><button className="flex h-11 w-11 items-center justify-center rounded-2xl border border-slate-200 bg-white"><ArrowLeft className="h-5 w-5" /></button></Link><div><h1 className="text-3xl font-bold">알림 설정</h1><p className="text-base text-slate-500">{mockUser.name}님 관련 알림</p></div></div></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><Bell className="h-6 w-6 text-cyan-700" />알림 받을 내용</CardTitle></CardHeader><CardContent className="space-y-3">{[["일일 상태 요약","매일 저녁 8시에 오늘 요약 전송",true],["체크인 누락","오후 2시까지 미체크인 시 알림",true],["복약 누락","예정 시간 2시간 경과 시 알림",true],["컨디션 저하","2일 연속 안 좋음 선택 시 알림",false]].map(([title, copy, on]) => <div key={String(title)} className="list-tile flex items-center justify-between"><div className="flex-1"><p className="text-lg font-bold">{title}</p><p className="text-sm text-slate-500">{copy}</p></div><div className={`flex h-8 w-14 items-center rounded-full px-1 ${on ? "justify-end bg-cyan-500" : "bg-slate-300"}`}><div className="h-6 w-6 rounded-full bg-white" /></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertCircle className="h-6 w-6 text-orange-600" />긴급 알림</CardTitle></CardHeader><CardContent><div className="rounded-[1.4rem] border border-orange-200 bg-orange-50 p-5"><p className="text-lg font-bold text-orange-950">도움 요청</p><p className="mt-1 text-sm text-orange-800">즉시 알림 (변경 불가)</p></div></CardContent></Card><Card className="bg-blue-50/80"><CardContent className="flex items-start gap-4 p-6"><Shield className="mt-1 h-7 w-7 text-blue-600" /><p className="text-base leading-7 text-blue-900/85">긴급 상황은 항상 즉시 알려드립니다. 그 외 알림은 과도하지 않도록 필요한 항목만 켜두는 것을 권장합니다.</p></CardContent></Card><div className="space-y-3"><Button className="w-full">설정 저장</Button><Link href="/caregiver"><Button variant="outline" className="w-full">돌아가기</Button></Link></div></div></div>;
}
